"""
Flow engine workflow: runs a dynamic sequence of agent-driven steps via Temporal,
with support for parallel execution and error resilience.
"""
from datetime import timedelta
from typing import Any, Dict, List, Optional
import asyncio

from temporalio import activity, workflow
from temporalio.client import Client
from temporalio.common import RetryPolicy

import orchestrator.services.config as config
from orchestrator.services.agent_registry import get_agent


if not hasattr(workflow, "WorkflowError"):
    class WorkflowError(Exception):
        """Aggregated workflow‐level error for failed steps."""
    setattr(workflow, "WorkflowError", WorkflowError)

@activity.defn
async def agent_activity(
    agent_name: str,
    params: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Activity that locates and executes the named agent with given parameters.
    May raise on failure; Temporal retry_policy applies automatically.
    """
    agent = get_agent(agent_name)
    result = await agent.run(params)
    return {"agent": agent_name, "output": result}


@workflow.defn
class ComplexSequenceWorkflow:
    """
    A Temporal workflow that executes a list of agents, optionally in parallel,
    with per-step retry and overall error aggregation.
    Each step dict may include:
      - name: agent name
      - params: dict for this step
      - parallel_with: list of other step dicts to run concurrently
      - retry: max retry count for failures
    """
    @workflow.run
    async def run(
        self,
        steps: List[Dict[str, Any]],
        payload: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        results: List[Dict[str, Any]] = []
        errors: List[str] = []

        async def _execute(step: Dict[str, Any]) -> Optional[Dict[str, Any]]:
            name = step.get("name")
            params = step.get("params", payload)
            retry_count = step.get("retry", 3)
            policy = RetryPolicy(initial_interval=timedelta(seconds=1), maximum_attempts=retry_count)
            try:
                return await workflow.execute_activity(
                    agent_activity,
                    name,
                    params,
                    start_to_close_timeout=timedelta(seconds=30),
                    retry_policy=policy,
                )
            except Exception as exc:
                return {"agent": name, "error": str(exc)}

        # Flatten into batches: either sequential singletons or parallel groups
        for step in steps:
            group = [step]
            # if parallel_with defined, include those
            if "parallel_with" in step:
                group = step["parallel_with"]
            # launch group
            tasks = [_execute(s) for s in group]
            batch_res = await asyncio.gather(*tasks)
            for res in batch_res:
                if res is None:
                    continue
                if "error" in res:
                    errors.append(f"{res['agent']}: {res['error']}")
                else:
                    results.append(res)

        if errors:
            # Optionally fail workflow or return partial
            raise workflow.WorkflowError(f"Errors executing steps: {errors}")

        return results


async def run_complex_workflow(
    steps: List[Dict[str, Any]],
    payload: Dict[str, Any],
    workflow_id: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Entry point to start the ComplexSequenceWorkflow via the Temporal client.

    Args:
        steps: List of dicts, each may include 'name', 'params', 'parallel_with', 'retry'.
        payload: Fallback payload for steps without explicit params.
        workflow_id: Optional ID; autogenerated if None.

    Returns:
        Results from all successful agent_activity executions.
    """
    client = await Client.connect(config.TEMPORAL_SERVER_URL)
    handle = await client.start_workflow(
        ComplexSequenceWorkflow.run,
        steps,
        payload,
        id=workflow_id,
        task_queue=config.TEMPORAL_TASK_QUEUE,
    )
    return await handle.result()
